# Generated by Django 3.1.1 on 2021-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
