# Generated by Django 3.1.1 on 2021-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0003_gamingpc_pcdes_pcpart_pcprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcpart',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
