# Generated by Django 3.1.1 on 2021-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va', '0004_pcpart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcpart',
            name='order',
        ),
        migrations.AddField(
            model_name='pcpart',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pcprice',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
